function ja_1(){
var rtn_value = true;
document.open();
document.writeln('  <table width="100%" border="0" cellspacing="0" cellpadding="0" class="pcTab">');
document.writeln('    <tr>');
document.writeln('      <td><a href="ja_1.html"><img src="script/img/s_hd_area01on.png" alt="ñkäCìπ ìåñk" width="554" height="183" border="0"></a></td>');
document.writeln('      <td><a href="ja_2.html"><img src="script/img/s_hd_area02.png" alt="ä÷ìå" width="554" height="183" border="0"></a></td>');
document.writeln('      <td><a href="ja_3.html"><img src="script/img/s_hd_area03.png" alt="ñkó§ çbêMâz" width="554" height="183" border="0"></a></td>');
document.writeln('      <td><a href="ja_4.html"><img src="script/img/s_hd_area04.png" alt="ìåäC" width="554" height="183" border="0"></a></td>');
document.writeln('      <td><a href="ja_5.html"><img src="script/img/s_hd_area05.png" alt="ãﬂãE" width="554" height="183" border="0"></a></td>');
document.writeln('      <td><a href="ja_6.html"><img src="script/img/s_hd_area06.png" alt="íÜçë" width="554" height="183" border="0"></a></td>');
document.writeln('      <td><a href="ja_7.html"><img src="script/img/s_hd_area07.png" alt="élçë" width="554" height="183" border="0"></a></td>');
document.writeln('      <td><a href="ja_8.html"><img src="script/img/s_hd_area08.png" alt="ã„èB â´ìÍ" width="554" height="183" border="0"></a></td>');
document.writeln('    </tr>');
//document.writeln('    <tr>');
//document.writeln('      <td colspan="8"><img src="script/img/line.png" alt="" width="100%" height="4" border="0"></td>');
//document.writeln('    </tr>');
document.writeln('  </table>');
document.writeln('  <table width="100%" border="0" cellspacing="0" cellpadding="0" class="spTab">');
document.writeln('    <tr>');
document.writeln('      <td><a href="ja_1.html"><img src="script/img/s_hd_area01on_sp.png" alt="ñkäCìπ ìåñk" width="384" height="184" border="0"></a></td>');
document.writeln('      <td><a href="ja_2.html"><img src="script/img/s_hd_area02_sp.png" alt="ä÷ìå" width="384" height="184" border="0"></a></td>');
document.writeln('      <td><a href="ja_3.html"><img src="script/img/s_hd_area03_sp.png" alt="ñkó§ çbêMâz" width="384" height="184" border="0"></a></td>');
document.writeln('      <td><a href="ja_4.html"><img src="script/img/s_hd_area04_sp.png" alt="ìåäC" width="384" height="184" border="0"></a></td>');
document.writeln('    </tr>');
document.writeln('  </table>');
document.writeln('  <table width="100%" border="0" cellspacing="0" cellpadding="0" class="spTab">');
document.writeln('    <tr>');
document.writeln('      <td><a href="ja_5.html"><img src="script/img/s_hd_area05_sp.png" alt="ãﬂãE" width="384" height="184" border="0"></a></td>');
document.writeln('      <td><a href="ja_6.html"><img src="script/img/s_hd_area06_sp.png" alt="íÜçë" width="384" height="184" border="0"></a></td>');
document.writeln('      <td><a href="ja_7.html"><img src="script/img/s_hd_area07_sp.png" alt="élçë" width="384" height="184" border="0"></a></td>');
document.writeln('      <td><a href="ja_8.html"><img src="script/img/s_hd_area08_sp.png" alt="ã„èB â´ìÍ" width="384" height="184" border="0"></a></td>');
document.writeln('    </tr>');
document.writeln('  </table>');
document.writeln('  <br>');
document.writeln('  <table width="100%" border="0" cellpadding="0" class="base" cellspacing="0">');
document.writeln('    <tr>');
document.writeln('      <td>');
document.writeln('        <table width="100%" border="0" cellpadding="2" cellspacing="1">');
document.writeln('          <tr class="spHead"> ');
document.writeln('            <th colspan="3" width="130" ></th>');
document.writeln('          </tr>');
document.writeln('          <tr class="pcHead"> ');
document.writeln('            <th width="130">î_ã∆ã¶ìØëgçáñº</th>');
document.writeln('            <th width="30">ójì˙</th>');
document.writeln('            <th width="125">Ç®à¯èoÇµÅEécçÇè∆âÔ</th>');
document.writeln('            <th width="125">Ç®óaì¸ÇÍ</th>');
document.writeln('          </tr>');
document.writeln('          <tr> ');
document.writeln('            <td rowspan="4" class="name" width="130" valign="middle" align="center"><span class="title">ÇiÇ`ÉoÉìÉNñkäCìπ</span><span class="subDating">Åi2016îN1åé1ì˙åªç›Åj</span></td>');
document.writeln('            <td  class="week">ïΩì˙</td>');
document.writeln('            <td class="time">8:00Å`22:00</td>');
document.writeln('            <td class="time">8:00Å`22:00</td>');
document.writeln('            </td>');
document.writeln('          </tr>');
document.writeln('          <tr> ');
document.writeln('            <td class="sat">ìyój</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('          </tr>');
document.writeln('          <tr> ');
document.writeln('            <td class="sun">ì˙ój</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('          </tr>');
document.writeln('          <tr> ');
document.writeln('            <td class="sun">èjì˙</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('          </tr>');
document.writeln('        </table>');
document.writeln('        <table width="100%" border="0" cellpadding="2" cellspacing="1">');
document.writeln('          <tr class="spHead"> ');
document.writeln('            <th colspan="3" width="130" ></th>');
document.writeln('          </tr>');
document.writeln('          <tr> ');
document.writeln('            <td rowspan="4" class="name" width="130" valign="middle" align="center"><span class="title">ÇiÇ`ÉoÉìÉNê¬êX</span><span class="subDating">Åi2016îN1åé1ì˙åªç›Åj</span></td>');
document.writeln('            <td  class="week">ïΩì˙</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('            </td>');
document.writeln('          </tr>');
document.writeln('          <tr> ');
document.writeln('            <td class="sat">ìyój</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('          </tr>');
document.writeln('          <tr> ');
document.writeln('            <td class="sun">ì˙ój</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('          </tr>');
document.writeln('          <tr class="borderBot"> ');
document.writeln('            <td class="sun">èjì˙</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('          </tr>');
document.writeln('        </table>');
document.writeln('        <table width="100%" border="0" cellpadding="2" cellspacing="1">');
document.writeln('          <tr class="spHead"> ');
document.writeln('            <th colspan="3" width="130" ></th>');
document.writeln('          </tr>');
document.writeln('          <tr> ');
document.writeln('            <td rowspan="4" class="name" width="130" valign="middle" align="center"><span class="title">ÇiÇ`ÉoÉìÉNä‚éË</span><span class="subDating">Åi2016îN1åé1ì˙åªç›Åj</span></td>');
document.writeln('            <td  class="week">ïΩì˙</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('            </td>');
document.writeln('          </tr>');
document.writeln('          <tr> ');
document.writeln('            <td class="sat">ìyój</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('          </tr>');
document.writeln('          <tr> ');
document.writeln('            <td class="sun">ì˙ój</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('          </tr>');
document.writeln('          <tr class="borderBot"> ');
document.writeln('            <td class="sun">èjì˙</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('          </tr>');
document.writeln('        </table>');
document.writeln('        <table width="100%" border="0" cellpadding="2" cellspacing="1">');
document.writeln('          <tr class="spHead"> ');
document.writeln('            <th colspan="3" width="130" ></th>');
document.writeln('          </tr>');
document.writeln('          <tr> ');
document.writeln('            <td rowspan="4" class="name" width="130" valign="middle" align="center"><span class="title">ÇiÇ`ÉoÉìÉNã{èÈ</span><span class="subDating">Åi2020îN1åé1ì˙åªç›Åj</span></td>');
document.writeln('            <td  class="week">ïΩì˙</td>');
document.writeln('            <td class="time">6:30Å`23:00</td>');
document.writeln('            <td class="time">6:30Å`23:00</td>');
document.writeln('            </td>');
document.writeln('          </tr>');
document.writeln('          <tr> ');
document.writeln('            <td class="sat">ìyój</td>');
document.writeln('            <td class="time">6:30Å`23:00</td>');
document.writeln('            <td class="time">6:30Å`23:00</td>');
document.writeln('          </tr>');
document.writeln('          <tr> ');
document.writeln('            <td class="sun">ì˙ój</td>');
document.writeln('            <td class="time">6:30Å`23:00</td>');
document.writeln('            <td class="time">6:30Å`23:00</td>');
document.writeln('          </tr>');
document.writeln('          <tr class="borderBot"> ');
document.writeln('            <td class="sun">èjì˙</td>');
document.writeln('            <td class="time">6:30Å`23:00</td>');
document.writeln('            <td class="time">6:30Å`23:00</td>');
document.writeln('          </tr>');
document.writeln('        </table>');
document.writeln('        <table width="100%" border="0" cellpadding="2" cellspacing="1">');
document.writeln('          <tr class="spHead"> ');
document.writeln('            <th colspan="3" width="130" ></th>');
document.writeln('          </tr>');
document.writeln('          <tr> ');
document.writeln('            <td rowspan="4" class="name" width="130" valign="middle" align="center"><span class="title">ÇiÇ`ÉoÉìÉNèHìc</span><span class="subDating">Åi2016îN1åé1ì˙åªç›Åj</span></td>');
document.writeln('            <td  class="week">ïΩì˙</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('            </td>');
document.writeln('          </tr>');
document.writeln('          <tr> ');
document.writeln('            <td class="sat">ìyój</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('          </tr>');
document.writeln('          <tr> ');
document.writeln('            <td class="sun">ì˙ój</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('          </tr>');
document.writeln('          <tr> ');
document.writeln('            <td class="sun">èjì˙</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('          </tr>');
document.writeln('        </table>');
document.writeln('      </td>');
document.writeln('    </tr>');
document.writeln('  </table>');
document.writeln('  <br>');
document.writeln('  <table width="100%" border="0" cellspacing="0" cellpadding="0">');
document.writeln('    <tr>');
document.writeln('      <td align="right"><img src="script/img/pagetop.gif" width="15" height="11" alt=""><a href="#top" class="nv">ÉyÅ[ÉWÇÃêÊì™Ç÷</a></td>');
document.writeln('    </tr>');
document.writeln('  </table>');
document.writeln('  <br>');
document.writeln('  <table width="100%" border="0" cellpadding="0" class="base" cellspacing="0">');
document.writeln('    <tr>');
document.writeln('      <td>');
document.writeln('        <table width="100%" border="0" cellpadding="2" cellspacing="1">');
document.writeln('          <tr class="spHead"> ');
document.writeln('            <th colspan="3" width="130" ></th>');
document.writeln('          </tr>');
document.writeln('          <tr class="pcHead"> ');
document.writeln('            <th width="130">î_ã∆ã¶ìØëgçáñº</th>');
document.writeln('            <th width="30">ójì˙</th>');
document.writeln('            <th width="125">Ç®à¯èoÇµÅEécçÇè∆âÔ</th>');
document.writeln('            <th width="125">Ç®óaì¸ÇÍ</th>');
document.writeln('          </tr>');
document.writeln('          <tr> ');
document.writeln('            <td rowspan="4" class="name" width="130" valign="middle" align="center"><span class="title">ÇiÇ`ÉoÉìÉNéRå`</span><span class="subDating">Åi2016îN1åé1ì˙åªç›Åj</span></td>');
document.writeln('            <td  class="week">ïΩì˙</td>');
document.writeln('            <td class="time">8:00Å`23:00</td>');
document.writeln('            <td class="time">8:00Å`23:00</td>');
document.writeln('            </td>');
document.writeln('          </tr>');
document.writeln('          <tr> ');
document.writeln('            <td class="sat">ìyój</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('          </tr>');
document.writeln('          <tr> ');
document.writeln('            <td class="sun">ì˙ój</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('          </tr>');
document.writeln('          <tr class="borderBot"> ');
document.writeln('            <td class="sun">èjì˙</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('            <td class="time">8:00Å`21:00</td>');
document.writeln('          </tr>');
document.writeln('        </table>');
document.writeln('        <table width="100%" border="0" cellpadding="2" cellspacing="1">');
document.writeln('          <tr class="spHead"> ');
document.writeln('            <th colspan="3" width="130" ></th>');
document.writeln('          </tr>');
document.writeln('          <tr> ');
document.writeln('            <td rowspan="4" class="name" width="130" valign="middle" align="center"><span class="title">ÇiÇ`ÉoÉìÉNïüìá</span><span class="subDating">Åi2016îN1åé1ì˙åªç›Åj</span></td>');
document.writeln('            <td  class="week">ïΩì˙</td>');
document.writeln('            <td class="time">7:00Å`23:00</td>');
document.writeln('            <td class="time">7:00Å`23:00</td>');
document.writeln('            </td>');
document.writeln('          </tr>');
document.writeln('          <tr> ');
document.writeln('            <td class="sat">ìyój</td>');
document.writeln('            <td class="time">7:00Å`23:00</td>');
document.writeln('            <td class="time">7:00Å`23:00</td>');
document.writeln('          </tr>');
document.writeln('          <tr> ');
document.writeln('            <td class="sun">ì˙ój</td>');
document.writeln('            <td class="time">7:00Å`23:00</td>');
document.writeln('            <td class="time">7:00Å`23:00</td>');
document.writeln('          </tr>');
document.writeln('          <tr> ');
document.writeln('            <td class="sun">èjì˙</td>');
document.writeln('            <td class="time">7:00Å`23:00</td>');
document.writeln('            <td class="time">7:00Å`23:00</td>');
document.writeln('          </tr>');
document.writeln('        </table>');
document.writeln('      </td>');
document.writeln('    </tr>');
document.writeln('  </table>');
document.close();
return rtn_value;
}